#!/bin/ash

# environment
PATH=/sbin:/usr/sbin:/bin:/usr/bin:$PATH
HOME=/root
LD_LIBRARY_PATH=/lib:/usr/lib:/bin
TMP=/tmp
HISTFILE=/tmp/.history
export LD_LIBRARY_PATH HISTFILE TMP
# path and home need to be fixed (busybox?)
export PATH HOME

# variables
MOD_DIR=/lib/modules/`/bin/uname -r`
SDCARD=/mnt/mmcblk1p1

[ -d $SDCARD ] || mkdir $SDCARD
mount -t vfat -o remount,rw /dev/mmcblk1p1 $SDCARD
sync
if [ -d $SDCARD/boot ] ; then
	errlog=$SDCARD/dmesg_1.txt
	dmesg > $errlog &
fi

fail() {
	#orange (warning)
	echo 1 > $LED_1
	echo 1 > $LED_2

	errlog=$SDCARD/dmesg_error.txt

	[ -d $SDCARD ] || (mkdir $SDCARD && mount -t vfat -o remount,rw /dev/mmcblk1p1 $SDCARD)

	/bin/echo "Failed: $1" > $errlog
	dmesg >> $errlog

	exec /bin/ash
}

mount -t proc  proc /proc -o noexec,nosuid,nodev
mount -t sysfs sysfs /sys -o noexec,nosuid,nodev
mount -t ramfs none /dev  -o exec,nosuid,mode=0755

mkdir -p /dev/pts /dev/shm /dev/input /mnt/disk
mount -t devpts devpts /dev/pts -o noexec,nosuid

USB_POWER=/sys/devices/platform/hhtech_gpio/usbotgdrv_en
LCD_LEVEL=/sys/devices/platform/s3c2410-lcd/backlight_level
GPIO=hhtech_gpio
if [ -d /sys/devices/platform/smartq_gpio ]; then
   # 2.6.31 (qdroid)
   GPIO=smartq_gpio
   LCD_LEVEL=/sys/devices/platform/s3c-lcd/backlight_level
fi

LED_1=/sys/devices/platform/$GPIO/led1_en
LED_2=/sys/devices/platform/$GPIO/led2_en

echo 1 > $LED_2
echo 0 > $LED_1

echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

if [ -f $MOD_DIR/kernel/drivers/video/host/s3c-fb.ko ] ; then
	modprobe s3c-fb
	[ $? -eq 0 ] || fail "Failed to modprobe s3c-fb. Cannot continue. $?"
fi
if [ -f $MOD_DIR/kernel/drivers/video/console/fbcon.ko ] ; then
	modprobe fbcon
	[ $? -eq 0 ] || fail "Failed to modprobe fbcon. Cannot continue. $?"
fi

#clear
fv /usr/magic.jpg &

# turn on lcd enable fb console and usb keyboard
echo 50 > $LCD_LEVEL

# 2.6.24
modprobe ohci_hcd &
# qdroid
# modprobe ohci-hcd & #or s3c_otg_hcd

modprobe usbhid &

# power mini USB port
echo 1 > $USB_POWER

# Load MMC SDCard Driver Module if Present
if [ -f $MOD_DIR/kernel/drivers/mmc/host/s3c-hsmmc.ko ] ; then
	modprobe s3c-hsmmc
	modprobe mmc_block
	usleep 500000
else
	#let the time to the logo to be paint
	usleep 300000
fi

# NumLock ON
for tty in /dev/tty[1-8]
do
    setleds -D +num < $tty > /dev/null
    echo "Console $tty - Press  Alt+Fn to switch" > $tty &
done

# clean other tty files
for tty in /dev/tty1[3-9] ; do rm $tty ; done
for tty in /dev/tty2[0-9] ; do rm $tty ; done
for tty in /dev/tty3[0-9] ; do rm $tty ; done
for tty in /dev/tty4[0-9] ; do rm $tty ; done
for tty in /dev/tty5[0-9] ; do rm $tty ; done
for tty in /dev/tty6[0-3] ; do rm $tty ; done

ln -s $SDCARD /sdcard

if [ -x $SDCARD/runme.sh ]
then
   getty -n -i -l $SDCARD/runme.sh 115200 tty1
else
   echo "no ./runme.sh script on SDCard"
fi

echo "SmartQ Magic SDCard
more tools will come...         http://tanguy.ath.cx - Sept 2010" > /dev/tty1 &

echo 0 > $LED_2

exec /bin/busybox init
