#!/bin/sh

make clean && \
make CPU=s3c6410

#make CPU=s3c2442 && \
#make CPU=s3c2410

# as root then...
#
# ./format-sd.sh sdb sdhc image/qi-s3c6410-andy_???????????????? x
# mount /dev/sdb2 /mnt ; cp ../kernel/linux-2.6/uImage.bin /mnt/boot ; umount /dev/sdb2

